### ISSUE TITLE
Dialog hide and then show after returning from background

### ISSUE THREAD

**Issue by Secretbox1987** [andrefrsousa/SuperBottomSheet#10]
How disable show dialog after returning to the app from background?

**Comment by andrefrsousa** [comment]
Hello @Secretbox1987,

If you don't what to, you just need to dismiss the bottom sheet when the app is resumed from the caller of the sheet. Example:

```
val findFragmentByTag = supportFragmentManager.findFragmentByTag("DemoBottomSheetFragment")
        (findFragmentByTag as AppCompatDialogFragment).dismiss()
```
