### ISSUE TITLE
problem with material 1.1.0-alpha10

### ISSUE THREAD

**Issue by MohammadB72** [andrefrsousa/SuperBottomSheet#12]
hii
when I use **1.1.0-alpha10**, got this **error message**
superbottomsheet.SuperBottomSheetDialog cannot be cast to com.google.android.material.bottomsheet.BottomSheetDialog

but when change material version to **1.1.0-alpha09** it's **worked correctly**

**Comment by andrefrsousa** [comment]
Hello @MohammadB72,

It seems a problem with the `alpha` library.  Anyhow, we are going to launch a new version of the library with AndroidX support.

PS - Take into account that `alpha` and `betas` are not supposed to be used in production 😉
