### ISSUE TITLE
Dismiss botttomsheet

### ISSUE THREAD

**Issue by CodeDruid13** [andrefrsousa/SuperBottomSheet#15]
Am trying to attach an onclick to a button to dismiss instead of swipe but it does not work, How do i implement this functionality?

**Comment by andrefrsousa** [comment]
Hello @CodeDruid13,

The bottom sheet is like a normal fragment, so in order to dismiss it you will have to do something like:

```
(supportFragmentManager.findFragmentByTag("YOUR TAG") as SuperBottomSheetFragment).dismiss()
``
