### ISSUE TITLE
Set NavigationBar custom color

### ISSUE THREAD

**Issue by caiovidaln** [andrefrsousa/SuperBottomSheet#17]
Hello, is there any simple way to change the color of the navigation bar when the fragment is active? I could not enter a custom color. It is turning a default gray when you open Bottom Sheet.

**Comment by andrefrsousa** [comment]
This is an issue from the Material components. Check this issue: https://github.com/material-components/material-components-android/issues/267

**Comment by demogorgorn** [comment]
With standard bottomsheet dialog from material all is working fine from the link you've posted. But with SBS not
