### ISSUE TITLE
background shadow transition was very unnatural

### ISSUE THREAD

**Issue by Merpyzf** [andrefrsousa/SuperBottomSheet#29]
Hello! After I upgraded from version 1.5.0 to version 2.0.0, when the Sheet dialog popped up from the screen, the background shadow transition was very unnatural.

The gif below shows the problem.
![](https://blog-1252413502.cos.ap-shanghai.myqcloud.com/Video_20210116_123625_570.gif)

Hope it can be optimized, thank you for your contribution！🍭

**Comment by Merpyzf** [comment]
gif picture address：
https://blog-1252413502.cos.ap-shanghai.myqcloud.com/Video_20210116_123625_570.gif

**Comment by amanzan** [comment]
I am noticing the same weird effect
