### ISSUE TITLE
Keyborad

### ISSUE THREAD

**Issue by mohodroid** [andrefrsousa/SuperBottomSheet#4]
how can move up bottom sheet when keyboard is visible?

**Comment by andrefrsousa** [comment]
Hello @mohodroid,

**Comment by andrefrsousa** [comment]
Hello @mohodroid,

This depends on your activity `windowSoftInputMode `.

To check what mode feats your issue, please take a look at this [documentation page](https://developer.android.com/training/keyboard-input/visibility).
