### ISSUE TITLE
colorPrimary is not getting overrided

### ISSUE THREAD

**Issue by mehul4795** [andrefrsousa/SuperBottomSheet#6]
In my app, all the three colors (colorPrimary, colorPrimaryDark and accentColor) are shades of Orange but still in the SuperBottomSheetFragment, I am seeing the default teal color everywhere.

**Comment by andrefrsousa** [comment]
Hello,

The `SuperBottomSheetFragment` colors are given by your application:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest>

    <application
        (...)
        android:theme="@style/AppTheme">

        (...)

    </application>

</manifest>
```

Are you changing the theme in runtime?

**Comment by n-apps** [comment]
Same problem/ I'm using material:1.2.0-alpha05
