### ISSUE TITLE
Bottom Sheet is not following the default wrap content behavior

### ISSUE THREAD

**Issue by mehul4795** [andrefrsousa/SuperBottomSheet#7]
I am showing the BottomSheet with few views in it and in spite of me using `wrap_content`, the BottomSheet uses default height leaving unnecessary padding at the bottom.

![screenshot_20190112-230608__01__01](https://user-images.githubusercontent.com/13131390/51076702-e51ea200-16c1-11e9-8f68-9340a629cb68.jpg)

**Comment by robertoestivill** [comment]
@mehul4795 did you find any workaround this issue?
Thanks

**Comment by ljesus** [comment]
Here's a workaround. Put this on your onStart():

```        
view?.viewTreeObserver?.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
                override fun onGlobalLayout() {
                    val behavior = BottomSheetBehavior.from(view!!.parent as View)
                    behavior.peekHeight = view!!.height
                    view?.viewTreeObserver?.removeOnGlobalLayoutListener(this)
                }
            })
```

**Comment by sabiou** [comment]
> Here's a workaround. Put this on your onStart():
> 
> ```
> view?.viewTreeObserver?.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
>                 override fun onGlobalLayout() {
>                     val behavior = BottomSheetBehavior.from(view!!.parent as View)
>                     behavior.peekHeight = view!!.height
>                     view?.viewTreeObserver?.removeOnGlobalLayoutListener(this)
>                 }
>             })
> ```

Hey ! this work but the bottomsheet is still draggable.. How to prevent it ?

**Comment by andrefrsousa** [comment]
HelloTo achieve it
